apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app: mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
      - name: mongodb-pvc
# keeping the persistentVolumeClain reference here even if I don't need one for statefulsets        
        # persistentVolumeClaim:
        #   claimName: mongodb-pvc
      containers:
      - name: mongodb
        image: mongo
        args: ["--dbpath","/data/db"]
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-pv
          mountPath: "/data/db"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
# volumeClaimTemplates replaces pvc for deployments, just use the name of the pv and it works              
  volumeClaimTemplates:
  - metadata:
      name: mongodb-pv
    spec:
      accessModes: 
      - ReadWriteOnce
      storageClassName: hostpath
      resources:
        requests:
          storage: 1Gi
# Headless service for statefulset
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
  clusterIP: None
  selector:
    app: mongodb