apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: practice
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
      - name: mongodb-pvc  
      containers:
      - name: mongodb
        image: mongo
        args: ["--dbpath","/data/db"]
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-pvc
          mountPath: "/data/db"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
  volumeClaimTemplates:
  - metadata:
      name: mongodb-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: hostpath
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: practice
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
  clusterIP: None
  selector:
    app: mongodb