apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express-ingress
  # annotations: kubernetes.io/ingress.class: "nginx"
  annotations: spec.ingressClassName: "nginx"
  namespace: practice
spec:
  rules:
    - host: mongoexpress.learn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mongo-express-service-internal
                port:
                  number: 8081
