apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    app: mongodb
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi   # Set the desired storage size
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /run/desktop/mnt/host/c/Temp/MongoDB/